Traceback (most recent call last):
  File "/Users/juliamaidannyk/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/juliamaidannyk/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/juliamaidannyk/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/juliamaidannyk/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/juliamaidannyk/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/juliamaidannyk/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/juliamaidannyk/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/juliamaidannyk/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df = h5py.File('Users/juliamaidannyk/Downloads/SPANet/0903_output_v5_matched.h5','r')
df_input = h5py.File('Users/juliamaidannyk/Downloads/SPANet/data/tth_matched_2.h5','r')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m df [38;5;241m=[39m [43mh5py[49m[38;5;241;43m.[39;49m[43mFile[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mUsers/juliamaidannyk/Downloads/SPANet/0903_output_v5_matched.h5[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      2[0m df_input [38;5;241m=[39m h5py[38;5;241m.[39mFile([38;5;124m'[39m[38;5;124mUsers/juliamaidannyk/Downloads/SPANet/data/tth_matched_2.h5[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m)

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py:406[0m, in [0;36mFile.__init__[0;34m(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)[0m
[1;32m    404[0m [38;5;28;01mwith[39;00m phil:
[1;32m    405[0m     fapl [38;5;241m=[39m make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0, [38;5;241m*[39m[38;5;241m*[39mkwds)
[0;32m--> 406[0m     fid [38;5;241m=[39m [43mmake_fid[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mmode[49m[43m,[49m[43m [49m[43muserblock_size[49m[43m,[49m
[1;32m    407[0m [43m                   [49m[43mfapl[49m[43m,[49m[43m [49m[43mfcpl[49m[38;5;241;43m=[39;49m[43mmake_fcpl[49m[43m([49m[43mtrack_order[49m[38;5;241;43m=[39;49m[43mtrack_order[49m[43m)[49m[43m,[49m
[1;32m    408[0m [43m                   [49m[43mswmr[49m[38;5;241;43m=[39;49m[43mswmr[49m[43m)[49m
[1;32m    410[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(libver, [38;5;28mtuple[39m):
[1;32m    411[0m     [38;5;28mself[39m[38;5;241m.[39m_libver [38;5;241m=[39m libver

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py:173[0m, in [0;36mmake_fid[0;34m(name, mode, userblock_size, fapl, fcpl, swmr)[0m
[1;32m    171[0m     [38;5;28;01mif[39;00m swmr [38;5;129;01mand[39;00m swmr_support:
[1;32m    172[0m         flags [38;5;241m|[39m[38;5;241m=[39m h5f[38;5;241m.[39mACC_SWMR_READ
[0;32m--> 173[0m     fid [38;5;241m=[39m [43mh5f[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mflags[49m[43m,[49m[43m [49m[43mfapl[49m[38;5;241;43m=[39;49m[43mfapl[49m[43m)[49m
[1;32m    174[0m [38;5;28;01melif[39;00m mode [38;5;241m==[39m [38;5;124m'[39m[38;5;124mr+[39m[38;5;124m'[39m:
[1;32m    175[0m     fid [38;5;241m=[39m h5f[38;5;241m.[39mopen(name, h5f[38;5;241m.[39mACC_RDWR, fapl[38;5;241m=[39mfapl)

File [0;32mh5py/_objects.pyx:54[0m, in [0;36mh5py._objects.with_phil.wrapper[0;34m()[0m

File [0;32mh5py/_objects.pyx:55[0m, in [0;36mh5py._objects.with_phil.wrapper[0;34m()[0m

File [0;32mh5py/h5f.pyx:88[0m, in [0;36mh5py.h5f.open[0;34m()[0m

[0;31mOSError[0m: Unable to open file (unable to open file: name = 'Users/juliamaidannyk/Downloads/SPANet/0903_output_v5_matched.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
OSError: Unable to open file (unable to open file: name = 'Users/juliamaidannyk/Downloads/SPANet/0903_output_v5_matched.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

